### ISSUE TITLE
AST-31 Discover and correct issue that prevents some items from SisterTalk batch ingest from playing back.

### ISSUE THREAD

**Issue by RayLubinsky** [uvalib/avalon#64]
ORIGINAL JIRA ISSUE Reporter   = md5wz (Mike Durbin)
ORIGINAL JIRA ISSUE Type       = Task
ORIGINAL JIRA ISSUE Priority   = Blocker
ORIGINAL JIRA ISSUE Status     = Done
ORIGINAL JIRA ISSUE Resolution = Fixed

In the original batch ingest of Sister Talk, many of the audio files did not play back in any system despite reporting successful transcode.

Upon further inspection it was discovered that the streaming derivatives were not present on disk.

Upon even further testing it became apparent that the derivatives **did** at one point exist, but were deleted sometime shortly after completion.

After a move to Wowza and a complete reinstall of matterhorn it was discovered that the "retract" workflow was being called (in some cases multiple times) for the missing videos, but it wasn't clear whether this was unexposed error handling within matterhorn, or something else.

After enabling much deeper logging in matterhorn and reinjesting the whole collection yet again, evidence was discovered that the avalon web application was in-fact issuing the revoke commands and logging them in logs/cleanup_jobs.log.

**Comment by RayLubinsky** [comment]
ORIGINAL JIRA COMMENT Author       = md5wz (Mike Durbin)

The revocation made through this call stack:

["/home/avalon/avalon-versions/avalon-3.2.1/app/models/derivative.rb:151:in `/'",
"/home/avalon/avalon-versions/avalon-3.2.1/app/models/derivative.rb:151:in `delete'",
"/home/avalon/avalon-versions/avalon-3.2.1/app/models/derivative.rb:91:in `map'",
"/home/avalon/avalon-versions/avalon-3.2.1/app/models/derivative.rb:91:in `create_from_master_file'",
"/home/avalon/avalon-versions/avalon-3.2.1/app/models/master_file.rb:334:in `block in update_progress_on_success!'",
"/home/avalon/avalon-versions/avalon-3.2.1/app/models/master_file.rb:333:in `each_pair'",
"/home/avalon/avalon-versions/avalon-3.2.1/app/models/master_file.rb:333:in `update_progress_on_success!'",
"/home/avalon/avalon-versions/avalon-3.2.1/app/controllers/master_files_controller.rb:155:in `update'",
"/home/avalon/.rvm/gems/ruby-2.1.5/gems/actionpack-4.0.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'",
"/home/avalon/.rvm/gems/ruby-2.1.5/gems/actionpack-4.0.11/lib/abstract_controller/base.rb:189:in `process_action'",
"/home/avalon/.rvm/gems/ruby-2.1.5/gems/actionpack-4.0.11/lib/action_controller/metal/rendering.rb:10:in `process_action'",
"/home/avalon/.rvm/gems/ruby-2.1.5/gems/actionpack-4.0.11/lib/abstract_controller/callbacks.rb:18:in `block in process_action'",

**Comment by RayLubinsky** [comment]
ORIGINAL JIRA COMMENT Author       = md5wz (Mike Durbin)

master_file.update_progress_on_success! is definitely called multiple times.

Possible reasons for this include:
1.  matterhorn sends the success multiple times (pretty unlikely)
2.  the pre-success updates come so quickly that when processed by master_file.update, the status has already changed to SUCCESS (a value that is requested out of band)

In either case, we need to ensure that the critical process (specifically the recreation, deletion and revocation of derivatives) does not execute extra times.

**Comment by RayLubinsky** [comment]
ORIGINAL JIRA COMMENT Author       = md5wz (Mike Durbin)

The following code fix seems to address this issue.  Due to a complete rework of the section of code for the next avalon release it's not clear whether the bug will exist (and require a comparable fix) or not.

https://github.com/uvalib/avalon/commit/48a5f3aacb40b8e593a61a6cf362a469c2ae73b8

**Comment by RayLubinsky** [comment]
ORIGINAL JIRA COMMENT Author       = md5wz (Mike Durbin)

This is fixed, but we should look out for it cropping up again after the next upgrade.
